
server:
  port: 8083

spring:
  main:
    web-application-type: reactive
    # Description:
    #
    #Spring MVC found on classpath, which is incompatible with Spring Cloud Gateway.
    #
    #Action:
    #
    #Please set spring.main.web-application-type=reactive or remove spring-boot-starter-web dependency.
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/awp?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: jwseo0204
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10


